### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Wolfyxon** [Wolfyxon/TurretSiege#2]
This is a task list for version releases.

# Planned features for each release

### 0.3.0 Alpha
- [ ] Fix game window being sometimes bigger than the screen
- [x] Pause menu
   - [x] Pausing logic
   - [x] Visual pause screen
   - [x] Resume button
   - [x] Menu button  
- [ ] Better weapons
  - [x] Weapon module system 
  - [ ] Switching
  - [x] Overheat 
  - [ ] More weapons
     - [ ] Machine gun (rapid fire, quick overheat) 
     - [ ] Cannon
- [x] Better class system
  - [x] Make a better class system
  - [x] Migrate most important classes to it
  - [x] Migrate everything else

# No release goal
- [ ] Tutorial
- [ ] Migrate to functional setup instead of assigning values and overriding functions for similar modules like projectiles, powerups, guns
  - [x] Guns
  - [ ] Projectiles
  - [ ] Power ups
- [ ] Reduce memory usage
- [ ] Full Android support
  - [ ] Screen joystick control mode (the current controlling is inconvenient on mobile)
  - [ ] Android build target for Lover 
- [ ] Use radians instead of degrees
- [ ] Use pixels for position instead of normalized values
- [ ] Boss fight
- [ ] Particle system
- [ ] Stronger enemies that fire bullets that can't be shot down. Those enemies have to be destroyed to stop their bullets.

# Urgent bugs
- Fix rendering performance
- [ ] #1
